// Package store persists brand-agent session state in SQLite.
//
// We use modernc.org/sqlite (pure-Go, CGO-free) so the binary stays
// single-file portable across Linux flavours without the libc / glibc /
// musl drama of CGO bindings. The schema is intentionally minimal: a
// `sessions` row carries everything needed to resume a multi-turn
// conversation and a `messages` row records each turn for audit and
// model-context replay.
//
// Migrations run on Open() via a simple "user_version" pragma — no
// migration library, no manifest file. New schema versions add a numbered
// step here and bump `currentSchemaVersion`.
package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"time"

	_ "modernc.org/sqlite"
)

const currentSchemaVersion = 3

type Store struct {
	db *sql.DB
}

type Session struct {
	SessionID     string
	SessionStatus string
	MediaBuyID    string
	OfferingID    string
	Placement     string
	Locale        string
	Intent        string
	ConsentGranted bool
	Identity      string // JSON blob
	Capabilities  string // JSON blob
	// InfluenceMode (M6.2 / schema v2) — string form of si.InfluenceMode,
	// stored verbatim so a downstream audit consumer can replay the
	// negotiation without needing the Go enum.
	InfluenceMode string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Message struct {
	SessionID string
	Turn      int
	Role      string // "host" or "brand"
	Content   string
	Payload   string // JSON blob (ui_elements etc.)
	CreatedAt time.Time
}

// Receipt is the M6.3 host-side sponsored_context_receipt as
// persisted. NotaryJWS is bragent's notarisation over (session_id,
// turn, sha256(raw_json), received_at) — signed with the same Ed25519
// key the M6.1 verify_brand_claim path uses. Lets a regulator (or a
// disputing host) verify cryptographically what bragent recorded
// receiving, even if no host-side request signature was present.
//
// Turn is the BRAND turn the receipt acknowledges (not the host turn
// that carried the receipt). For receipts arriving on
// si_initiate_session about a pre-session si_get_offering, Turn is -1.
type Receipt struct {
	SessionID    string
	Turn         int
	RawJSON      string
	NotaryJWS    string
	ReceivedAt   time.Time
	Accepted     bool
	AcceptedUse  string // empty when Accepted is false
	Synthesised  bool   // true when receipt was generated by the MCP bridge, not a real host
}

// Open opens (or creates) the SQLite database at path and runs migrations.
// Pass `:memory:` for ephemeral runs (tests, --simulate-host smoke loops).
func Open(path string) (*Store, error) {
	db, err := sql.Open("sqlite", path)
	if err != nil {
		return nil, fmt.Errorf("open sqlite %s: %w", path, err)
	}
	// SQLite + Go: single connection avoids busy errors on concurrent writers
	// without needing WAL gymnastics. Brand-agent traffic is low enough that
	// this is the right tradeoff; revisit if a session ever needs streaming.
	db.SetMaxOpenConns(1)

	s := &Store{db: db}
	if err := s.migrate(); err != nil {
		_ = db.Close()
		return nil, err
	}
	return s, nil
}

func (s *Store) Close() error { return s.db.Close() }

func (s *Store) migrate() error {
	var v int
	if err := s.db.QueryRow("PRAGMA user_version").Scan(&v); err != nil {
		return fmt.Errorf("read user_version: %w", err)
	}
	if v >= currentSchemaVersion {
		return nil
	}
	if v < 1 {
		if _, err := s.db.Exec(`
			CREATE TABLE sessions (
				session_id      TEXT PRIMARY KEY,
				session_status  TEXT NOT NULL,
				media_buy_id    TEXT,
				offering_id     TEXT,
				placement       TEXT,
				locale          TEXT,
				intent          TEXT,
				consent_granted INTEGER NOT NULL DEFAULT 0,
				identity_json   TEXT,
				capabilities_json TEXT,
				created_at      TEXT NOT NULL,
				updated_at      TEXT NOT NULL
			);
			CREATE TABLE messages (
				session_id  TEXT NOT NULL REFERENCES sessions(session_id),
				turn        INTEGER NOT NULL,
				role        TEXT NOT NULL,
				content     TEXT NOT NULL,
				payload     TEXT,
				created_at  TEXT NOT NULL,
				PRIMARY KEY (session_id, turn)
			);
		`); err != nil {
			return fmt.Errorf("schema v1: %w", err)
		}
	}
	if v < 2 {
		// M6.2 — add influence_mode column. The column NAME stays
		// `influence_mode` for DB compatibility; M6.3's Go field name
		// is ContextUse but the on-disk artifact keeps the M6.2 label.
		if _, err := s.db.Exec(`ALTER TABLE sessions ADD COLUMN influence_mode TEXT`); err != nil {
			return fmt.Errorf("schema v2: %w", err)
		}
	}
	if v < 3 {
		// M6.3 — new receipts table for sponsored_context_receipt
		// persistence with cryptographic notarisation. Turn = -1 is
		// reserved for receipts arriving on si_initiate_session that
		// acknowledge a pre-session si_get_offering.
		if _, err := s.db.Exec(`
			CREATE TABLE receipts (
				session_id   TEXT NOT NULL REFERENCES sessions(session_id),
				turn         INTEGER NOT NULL,
				raw_json     TEXT NOT NULL,
				notary_jws   TEXT,
				received_at  TEXT NOT NULL,
				accepted     INTEGER NOT NULL,
				accepted_use TEXT,
				synthesised  INTEGER NOT NULL DEFAULT 0,
				PRIMARY KEY (session_id, turn)
			);
		`); err != nil {
			return fmt.Errorf("schema v3: %w", err)
		}
	}
	if _, err := s.db.Exec(fmt.Sprintf("PRAGMA user_version = %d", currentSchemaVersion)); err != nil {
		return fmt.Errorf("set user_version: %w", err)
	}
	return nil
}

func (s *Store) CreateSession(ctx context.Context, sess Session) error {
	if sess.CreatedAt.IsZero() {
		sess.CreatedAt = time.Now().UTC()
	}
	if sess.UpdatedAt.IsZero() {
		sess.UpdatedAt = sess.CreatedAt
	}
	_, err := s.db.ExecContext(ctx, `
		INSERT INTO sessions (
			session_id, session_status, media_buy_id, offering_id, placement,
			locale, intent, consent_granted, identity_json, capabilities_json,
			influence_mode, created_at, updated_at
		) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`,
		sess.SessionID, sess.SessionStatus, sess.MediaBuyID, sess.OfferingID, sess.Placement,
		sess.Locale, sess.Intent, boolToInt(sess.ConsentGranted), sess.Identity, sess.Capabilities,
		sess.InfluenceMode, sess.CreatedAt.Format(time.RFC3339Nano), sess.UpdatedAt.Format(time.RFC3339Nano),
	)
	if err != nil {
		return fmt.Errorf("insert session %s: %w", sess.SessionID, err)
	}
	return nil
}

func (s *Store) AppendMessage(ctx context.Context, m Message) error {
	if m.CreatedAt.IsZero() {
		m.CreatedAt = time.Now().UTC()
	}
	_, err := s.db.ExecContext(ctx, `
		INSERT INTO messages (session_id, turn, role, content, payload, created_at)
		VALUES (?,?,?,?,?,?)`,
		m.SessionID, m.Turn, m.Role, m.Content, m.Payload, m.CreatedAt.Format(time.RFC3339Nano),
	)
	if err != nil {
		return fmt.Errorf("insert message %s/%d: %w", m.SessionID, m.Turn, err)
	}
	return nil
}

func (s *Store) GetSession(ctx context.Context, id string) (*Session, error) {
	var sess Session
	var consent int
	var createdAt, updatedAt string
	var influenceMode sql.NullString
	err := s.db.QueryRowContext(ctx, `
		SELECT session_id, session_status, media_buy_id, offering_id, placement,
		       locale, intent, consent_granted, identity_json, capabilities_json,
		       influence_mode, created_at, updated_at
		FROM sessions WHERE session_id = ?`, id,
	).Scan(
		&sess.SessionID, &sess.SessionStatus, &sess.MediaBuyID, &sess.OfferingID, &sess.Placement,
		&sess.Locale, &sess.Intent, &consent, &sess.Identity, &sess.Capabilities,
		&influenceMode, &createdAt, &updatedAt,
	)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("get session %s: %w", id, err)
	}
	sess.ConsentGranted = consent == 1
	// Pre-M6.2 sessions have NULL influence_mode; coerce to the safe
	// default so replay/audit code never sees an empty string.
	if influenceMode.Valid && influenceMode.String != "" {
		sess.InfluenceMode = influenceMode.String
	} else {
		sess.InfluenceMode = "presentation_only"
	}
	sess.CreatedAt, _ = time.Parse(time.RFC3339Nano, createdAt)
	sess.UpdatedAt, _ = time.Parse(time.RFC3339Nano, updatedAt)
	return &sess, nil
}

func (s *Store) UpdateSessionStatus(ctx context.Context, id, status string) error {
	now := time.Now().UTC().Format(time.RFC3339Nano)
	res, err := s.db.ExecContext(ctx,
		`UPDATE sessions SET session_status = ?, updated_at = ? WHERE session_id = ?`,
		status, now, id,
	)
	if err != nil {
		return fmt.Errorf("update session %s: %w", id, err)
	}
	rows, _ := res.RowsAffected()
	if rows == 0 {
		return fmt.Errorf("session %s not found", id)
	}
	return nil
}

// ListMessages returns the full turn log for a session, oldest first.
// Used by si_send_message to feed prior turns into the mock LLM so its
// replies stay context-aware across the conversation.
func (s *Store) ListMessages(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := s.db.QueryContext(ctx,
		`SELECT session_id, turn, role, content, payload, created_at
		   FROM messages WHERE session_id = ? ORDER BY turn ASC`,
		sessionID,
	)
	if err != nil {
		return nil, fmt.Errorf("list messages %s: %w", sessionID, err)
	}
	defer rows.Close()
	var out []Message
	for rows.Next() {
		var m Message
		var createdAt string
		if err := rows.Scan(&m.SessionID, &m.Turn, &m.Role, &m.Content, &m.Payload, &createdAt); err != nil {
			return nil, err
		}
		m.CreatedAt, _ = time.Parse(time.RFC3339Nano, createdAt)
		out = append(out, m)
	}
	return out, rows.Err()
}

// NextTurn returns the next turn number for a session. Callers use this
// to stamp messages atomically with the session row update.
func (s *Store) NextTurn(ctx context.Context, sessionID string) (int, error) {
	var n int
	err := s.db.QueryRowContext(ctx,
		`SELECT COALESCE(MAX(turn), -1) + 1 FROM messages WHERE session_id = ?`,
		sessionID,
	).Scan(&n)
	if err != nil {
		return 0, fmt.Errorf("next turn %s: %w", sessionID, err)
	}
	return n, nil
}

// SaveReceipt persists a sponsored_context_receipt with its bragent
// notarisation. Idempotent on (session_id, turn) — replays overwrite,
// which matters when a host retries an si_send_message that carried a
// receipt. Last-write-wins is fine because the receipt content is
// what the host meant on its most recent attempt.
func (s *Store) SaveReceipt(ctx context.Context, r Receipt) error {
	if r.ReceivedAt.IsZero() {
		r.ReceivedAt = time.Now().UTC()
	}
	_, err := s.db.ExecContext(ctx, `
		INSERT INTO receipts (session_id, turn, raw_json, notary_jws, received_at, accepted, accepted_use, synthesised)
		VALUES (?,?,?,?,?,?,?,?)
		ON CONFLICT(session_id, turn) DO UPDATE SET
			raw_json     = excluded.raw_json,
			notary_jws   = excluded.notary_jws,
			received_at  = excluded.received_at,
			accepted     = excluded.accepted,
			accepted_use = excluded.accepted_use,
			synthesised  = excluded.synthesised`,
		r.SessionID, r.Turn, r.RawJSON, r.NotaryJWS,
		r.ReceivedAt.Format(time.RFC3339Nano),
		boolToInt(r.Accepted), r.AcceptedUse, boolToInt(r.Synthesised),
	)
	if err != nil {
		return fmt.Errorf("save receipt %s/%d: %w", r.SessionID, r.Turn, err)
	}
	return nil
}

// ListReceipts returns all receipts for a session in turn order.
// Negative turn (-1) — the pre-session offering acknowledgement —
// sorts first naturally.
func (s *Store) ListReceipts(ctx context.Context, sessionID string) ([]Receipt, error) {
	rows, err := s.db.QueryContext(ctx,
		`SELECT session_id, turn, raw_json, notary_jws, received_at, accepted, accepted_use, synthesised
		   FROM receipts WHERE session_id = ? ORDER BY turn ASC`,
		sessionID,
	)
	if err != nil {
		return nil, fmt.Errorf("list receipts %s: %w", sessionID, err)
	}
	defer rows.Close()
	var out []Receipt
	for rows.Next() {
		var r Receipt
		var notary sql.NullString
		var acceptedUse sql.NullString
		var receivedAt string
		var accepted, synth int
		if err := rows.Scan(&r.SessionID, &r.Turn, &r.RawJSON, &notary, &receivedAt, &accepted, &acceptedUse, &synth); err != nil {
			return nil, err
		}
		if notary.Valid {
			r.NotaryJWS = notary.String
		}
		if acceptedUse.Valid {
			r.AcceptedUse = acceptedUse.String
		}
		r.ReceivedAt, _ = time.Parse(time.RFC3339Nano, receivedAt)
		r.Accepted = accepted == 1
		r.Synthesised = synth == 1
		out = append(out, r)
	}
	return out, rows.Err()
}

// MarshalIdentity is a tiny helper so callers don't import encoding/json
// to stash an Identity blob in the session row.
func MarshalIdentity(v any) (string, error) {
	if v == nil {
		return "", nil
	}
	b, err := json.Marshal(v)
	if err != nil {
		return "", err
	}
	return string(b), nil
}

func boolToInt(b bool) int {
	if b {
		return 1
	}
	return 0
}
